### ISSUE TITLE
OpenJDK purge error

### ISSUE THREAD

**Issue by paulbuis** [r-a-p-a/mint-dev-box#1]
In developer.sh the line "apt purge openjdk" produces an error message. Perhaps it needs to be more specific about what mint openjdk package needs to be removed. openjdk-7-jre-headless, maybe? Having some openjdk laying around after the Oracle Java 8 stuff is installed doesn't seem to cause real problems....

**Comment by RustyD** [comment]
Having the openjdk lying around isn't a problem, as you have said. It was being (unseccessfully) removed to reduce the size of the end box. I'll try a more specific 'openjdk-7-jre'.

**Comment by paulbuis** [comment]
OK, not a serious problem, it wasn't clear why openjdk was being uninstalled. I typically uninstall it manually and replace it with Oracle's JDK when I prep an image, just to reduce confusion on the part of users, but I wasn't sure if it caused problems with scala or something like that...
