### ISSUE TITLE
complete.sh error message when running "versions"

### ISSUE THREAD

**Issue by paulbuis** [r-a-p-a/mint-dev-box#2]
Line 17 of scripts/complete.sh invokes the command "versions" 

I'm assuming the intent was to invoke files/versions.

Instead, I got an error message /usr/local/bin/versions: Permission Denied

**Comment by RustyD** [comment]
So mint.json lines 50-54 should provision the 'versions' file to /tmp in the virtual machine.

developer.sh line 139 should copy that from /tmp to /usr/local/bin (in the vm).

complete.sh should execute as sudo/root (the same as developer.sh) and not have a problem executing the versions file in /usr/local/bin

It has worked ok the couple of times I tried it myself this morning, so I am a bit puzzled. It should also be executable by the 'vagrant' user once you've 'up-d' the box into a vm.

**Comment by paulbuis** [comment]
Thanks for explaining the flow involved.

After the machine I got from the atlas repo is up, I had no problems running /usr/local/bin/versions and I also can't see why the error message was generated during the packer run. Clearly, since it is owned by root with 755 permissions, so should be world readable & executable. I did reproduce it on my later runs of packer, but it is not a show-stopper.
