### ISSUE TITLE
Error removing floppy: VBoxManage error

### ISSUE THREAD

**Issue by paulbuis** [r-a-p-a/mint-dev-box#3]
I'm running VirtualBox 5.0.20 under windows. At the end of the Packer run, I got the very disappointing messages:

==> virtualbox-iso: Gracefully halting virtual machine...
    virtualbox-iso: Removing floppy drive...
==> virtualbox-iso: Error removing floppy: VBoxManage error: VBoxManage.exe: err
or: Failed to get a console object from the direct session (VBOX_E_INVALID_OBJEC
T_STATE)
==> virtualbox-iso: VBoxManage.exe: error: Details: code VBOX_E_VM_ERROR (0x80bb
0003), component MachineWrap, interface IMachine, callee IUnknown
==> virtualbox-iso: VBoxManage.exe: error: Context: "LockMachine(a->session, Loc
kType_Shared)" at line 326 of file VBoxManageStorageController.cpp
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Error removing floppy: VBoxManage error: VBoxMan
age.exe: error: Failed to get a console object from the direct session (VBOX_E_I
NVALID_OBJECT_STATE)
VBoxManage.exe: error: Details: code VBOX_E_VM_ERROR (0x80bb0003), component Mac
hineWrap, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Shared)" at li
ne 326 of file VBoxManageStorageController.cpp

**Comment by RustyD** [comment]
I have not seen that error myself, and a quick google reveals that others seem to have a similar issue. It might be a windows specific issue (my host is Linux Mint 17.3), or some sort of 'timing' issue. I don't think there is much that I can do about it?

**Comment by paulbuis** [comment]
Ok, I'll try running packer in a non-Windows environment. It looks like a problem between packer and Virtualbox and specific to Windows, not a problem with your code.

**Comment by paulbuis** [comment]
Yup, this is a packer issue on their GItHub issue tracker: https://github.com/mitchellh/packer/issues/2401

**Comment by paulbuis** [comment]
Based on the discussion of the GitHub issue tracker, I changed the line in mint.json to hard code the value of "headless" to true and the packer build process completed successfully!

**Comment by RustyD** [comment]
I would have thought that 'headless' was totally unrelated to the 'floppy drive' - but what do I know?!
